<template><p align="center">
    <a href="https://github.com/danielkauffmann/poodle">
        <img src="/images/rlogo.png" width="200" height="200" alt="Moodle Organizer Bot" >
    </a>
</p>
<p><a href="https://pypi.org/project/poodle/" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/pypi/v/poodle" alt="PyPi Package Version"><OutboundLink/></a>
<a href="https://pypi.org/project/poodle/" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/pypi/pyversions/poodle" alt="Supported Python versions"><OutboundLink/></a>
<a href="https://github.com/danielkauffmann/poodle/blob/master/LICENSE" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/license/danielkauffmann/poodle" alt="LICENSE"><OutboundLink/></a>
<a href="https://codecov.io/gh/danielkauffmann/poodle" target="_blank" rel="noopener noreferrer"><img src="https://codecov.io/gh/danielkauffmann/poodle/branch/main/graph/badge.svg?token=D7OI3GWKRT" alt="codecov"><OutboundLink/></a></p>
<h1 id="introduction" tabindex="-1"><a class="header-anchor" href="#introduction" aria-hidden="true">#</a> Introduction</h1>
<p>Poodle is an integration written in Python with the Moodle Web Service (MWS) APIs. The interaction is done through the
features mapped and made available natively by Moodle and were built to facilitate the extraction
of these data.</p>
<p>Currently, this project together with <a href="https://github.com/lsglucas/mob" target="_blank" rel="noopener noreferrer">Moodle Organizer Bot<OutboundLink/></a> form an application
large and complex where it aims to integrate Moodle into the Discord environment for any learning platforms.</p>
<h2 id="how-it-works" tabindex="-1"><a class="header-anchor" href="#how-it-works" aria-hidden="true">#</a> How it works</h2>
<p>Through an access token generated by <a href="https://moodle.org/" target="_blank" rel="noopener noreferrer">Moodle<OutboundLink/></a>, it is possible to interact with all available APIs
and Poodle is here to facilitate this process, as well as providing optimized and performance-enhancing features accordingly.
with data demand.</p>
<p>Due to the purpose currently used, all documentation on data formatting is extremely
detailed while there is no need to generalize the application. Remembering that there are other implementations with the
same idea, such as <a href="https://github.com/hexatester/moodlepy" target="_blank" rel="noopener noreferrer">moodlepy<OutboundLink/></a> which has a role to meet demands
generic MWS.</p>
<h2 id="motivation" tabindex="-1"><a class="header-anchor" href="#motivation" aria-hidden="true">#</a> Motivation</h2>
<p>One day we were at Discord playing Rocket League, and we realized it was time for class.
At that, the following conversation arose:</p>
<div style="display: flex; width: fit-content; margin-bottom: 1rem; padding: .4rem; background-color: rgba(70, 70, 70, 0.3); border-radius: 10px;">
    <img style="border-radius: 50%" src="https://avatars.githubusercontent.com/u/61513630?v=4" width="32px;" alt="Lucas"/>
    <div style="align-self: center; margin-left: .5rem; font-size: .8rem">
        we could have some way of knowing when the classes are through Discord, right?
    </div>
</div>
<div style="display: flex; width: fit-content; margin-left: auto; margin-bottom: 1rem; padding: .4rem; background-color: rgba(70, 70, 70, 0.3); border-radius: 10px;">
    <div style="align-self: center; margin-right: .5rem; font-size: .8rem">
        if Moodle has API we could LMAO
    </div>
    <img style="border-radius: 50%" src="https://avatars.githubusercontent.com/u/62577994?v=4" width="32px;" alt="Daniel"/>
</div>
<div style="display: flex; width: fit-content; margin-bottom: 1rem; padding: .4rem; background-color: rgba(70, 70, 70, 0.3); border-radius: 10px;">
    <img style="border-radius: 50%" src="https://avatars.githubusercontent.com/u/61513630?v=4" width="32px;" alt="Lucas"/>
    <div style="align-self: center; margin-left: .5rem; font-size: .8rem">
        broo, lol
    </div>
</div>
<div style="display: flex; width: fit-content; margin-left: auto; margin-bottom: 1rem; padding: .4rem; background-color: rgba(70, 70, 70, 0.3); border-radius: 10px;">
    <div style="align-self: center; margin-right: .5rem; font-size: .8rem">
        I'll take a look to see if I can find something
    </div>
    <img style="border-radius: 50%" src="https://avatars.githubusercontent.com/u/62577994?v=4" width="32px;" alt="Daniel"/>
</div>
<p>Days later I came back with the news that this API really existed and had found the
<a href="https://docs.moodle.org/dev/Web_service_API_functions" target="_blank" rel="noopener noreferrer">official documentation<OutboundLink/></a> for different functionality, just
it was enough to find out if our university (<a href="https://www.mackenzie.br/" target="_blank" rel="noopener noreferrer">UPM<OutboundLink/></a>) had these public resources.
A few more days later, we validated our theory and proceeded to develop the idea.</p>
<p>So then came the idea of building this integration, and we were improving the idea until we reached the model where
there would be a Bot in Discord.
It will be responsible for sending notices about assignments and viewing classes during the week.
From this moment on, our creativity took off, and we didn't stop until then.</p>
<h2 id="creators" tabindex="-1"><a class="header-anchor" href="#creators" aria-hidden="true">#</a> Creators</h2>
<p>Lucas and I (Daniel) are pleased to develop this project together, producing our ideas and making it available
for anyone to take advantage of and help us improve the project. We hope you always take some learning!</p>
<table>
  <tr>
    <td align="center">
      <a href="https://github.com/danielkauffmann">
        <img src="https://avatars.githubusercontent.com/u/62577994?v=4" width="150px;" alt="Daniel Kauffmann"/>
        <br />
        <a href="https://github.com/danielkauffmann">
          <b>Daniel Kauffmann</b>
        </a>
        <br />
        <p style="font-size: 2rem">
          <a href="mailto:vkdaniel@icloud.com">
            <img src="https://img.icons8.com/emoji/32/000000/envelope-.png" alt="E-mail"/>
          </a>
          <a href="https://www.linkedin.com/in/danielkauffmann">
            <img src="https://img.icons8.com/color/32/000000/linkedin.png" alt="Linkedin"/>
          </a>
          <a href="https://twitter.com/danieldowombo">
            <img src="https://img.icons8.com/fluency/32/000000/twitter--v3.png" alt="Twitter"/>
          </a>
        </p>
      </a>
    </td>
    <td align="center">
      <a href="https://github.com/lsglucas">
        <img src="https://avatars.githubusercontent.com/u/61513630?v=4" width="150px;" alt="Lucas Garcia"/>
        <br />
        <a href="https://github.com/lsglucas">
          <b>Lucas Garcia</b>
        </a>
        <br />
        <p style="font-size: 2rem">
          <a href="mailto:lsglucas@pm.me">
            <img src="https://img.icons8.com/emoji/32/000000/envelope-.png" alt="E-mail"/>
          </a>
          <a href="https://www.linkedin.com/in/lsglucas">
            <img src="https://img.icons8.com/color/32/000000/linkedin.png" alt="Linkedin"/>
          </a>
          <a href="https://twitter.com/lsglucass">
            <img src="https://img.icons8.com/fluency/32/000000/twitter--v3.png" alt="Twitter"/>
          </a>
        </p>
      </a>
    </td>
  </tr>
</table></template>
